#!/bin/bash

#АВТОСТАРТ
sxhkd &
numlockx &
xsetroot -cursor_name left_ptr
$HOME/.fehbg
$HOME/.config/eww/bar/scripts/weather get &
eww -c ~/.config/eww/bar open bar
$HOME/.config/eww/bar/scripts/metrics subscribe &
picom -b
copyq &
lxqt-policykit-agent &
nm-applet &
blueman-applet &
udiskie -f vifmlaunch --tray &
$HOME/.config/eww/bar/scripts/task_manager monitor

#ВОРКСПЕЙСЫ
bspc monitor -d 1 2 3 4 5

bspc config pointer_motion_interval 5

#РАМКИ И ГАПСЫ
bspc config border_width         0
bspc config window_gap          10

bspc config normal_border_color "#23252e"
bspc config active_border_color "#23252e"
bspc config focused_border_color "#f9f8fe"

#ЦВЕТ ПРОСТРАНСТВА ПРИ ВЫБОРЕ ПОЛОЖЕНИЯ НОВОГО ОКНА
bspc config presel_feedback_color "#0050AA"

#КОФИЦИЕНТ РАЗДЕЛЕНИЯ, СКОЛЬКО ПРОЦЕНТОВ ОСТАНЕТСЯ ОТ РОДИТЕЛЬСКОГО ОКНА ПРИ ОТКРЫТИИ НОВОГО
bspc config split_ratio          0.5

#ФОКУС ОКНА НАВЕДЕНИЕМ КУРСОРА
bspc config focus_follows_pointer true
bspc config pointer_modifier	super

#РЕЖИМ МОНОКЛЯ КОГДА ОТКРЫТО ОДНО ОКНО
bspc config single_monocle true

#ОТКЛЮЧЕНИЕ ГАПСОВ РАМОК И ОТСТУПОВ КОГДА ОТКРЫТО ОДНО ОКНО
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config paddingless_monocle	 true


#СХЕМЫ СОГЛАСНО КОТОРЫМ БУДУТ ОТКРЫВАТСЯ ОКНА
# bspc config automatic_scheme alternate


#ПРАВИЛА ОКОН
bspc rule -a firefox rectangle=1200x771+355+181
bspc rule -a tabbed rectangle=828x451+533+324
bspc rule -a win_translate state=floating
bspc rule -a Hubstaff state=floating
bspc rule -a vlc state=floating
bspc rule -a float_alacritty state=floating
bspc rule -a zoom state=floating
bspc rule -a Nm-connection-editor state=floating
bspc rule -a discord state=floating
bspc rule -a TelegramDesktop state=floating
bspc rule -a transmission-gtk state=floating
bspc rule -a copyq state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Blueman-manager state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a Lxappearance rectangle=870x477+317+272
bspc rule -a appium-inspector state=floating
bspc rule -a Vncviewer state=floating
bspc rule -a "VirtualBox Manager" state=floating
bspc rule -a VirtualBox state=floating
bspc rule -a Hubstaff state=floating
bspc config external_rules_command /home/nikita/.config/bspwm/external_rules

