#!/bin/bash

wid=$1
title=$(xtitle "$wid")

[[ "$title" == 'Android Emulator -'* ]] && echo "state=pseudo_tiled rectangle=320x640-63+220"

[[ "$title" == *' - TigerVNC' ]] && [[ ! $(echo $title | grep -Eo "\([^)]+\)") ]] && echo "rectangle=417x697+447+129"

[[ "$title" == *' - TigerVNC' ]] && [[ $(echo $title | grep -Eo "\([^)]+\)") ]] && echo "state=pseudo_tiled rectangle=1720x936+90+60"

