#!/bin/bash

wid=$1
wclass=$(xprop -id $wid | grep WM_CLASS | grep -Eo "\"[^, ]+\"" | head -n1)
title=$(xtitle "$wid")

[[ "$wclass" == '"scratchpad"' ]] && echo "hidden=true state=floating sticky=true locked=true"

[[ "$title" == 'Android Emulator*' ]] && (( $(xprop -id $wid | grep "user specified size" | awk '{print $4}') > 70 )) && echo "state=pseudo_tiled rectangle=320x640-63+237"

[[ "$title" == *' - TigerVNC' ]] && [[ ! $(echo $title | grep -Eo "\([^)]+\)") ]] && echo "rectangle=417x697+447+129"

[[ "$title" == *' - TigerVNC' ]] && [[ $(echo $title | grep -Eo "\([^)]+\)") ]] && echo "state=pseudo_tiled rectangle=1720x936+90+60"

