#!/bin/env bash

function get_port() {
  echo $(sudo ss -4tlp | grep sshd | awk '{print $4}' | cut -d: -f2)
}

pid=$(ps -A | grep 'sshd' | awk '{print $1}')

if [ "$pid" != "" ]; then
  echo -e "SSHD already working!\n"
  read -p "Press any key to exit..."
else
  termux-wake-lock

  sshd -o ListenAddress=127.0.0.1

  pid=$(ps -A | grep 'sshd' | awk '{print $1}')

  echo -e "SSHD was started!\n"`
         `"PID: ${pid}\n"`
         `"IP address: 127.0.0.1\n"`
         `"Port: $(get_port)\n"`
         `"User: $(whoami)\n"`
         `"Home: /data/data/com.termux/files/home\n\n"

  read -p "Press any key to stop SSHD"

  kill $pid
  echo -e "SSHD was stopped!\n\n"
  termux-wake-unlock
fi

