#!/bin/sh

bat=/sys/class/power_supply/BAT1/
per="$(cat "$bat/capacity")"
crit_file=/tmp/eww_states/bat.crit

icon() {

if [ "$per" -e "100" ]; then
  if [ $(cat "$bat/status") = Charging ]; then
	  [ ! -f /tmp/eww_states/notify.lock ] && notify-send -t 2000 "Battery Full" "Unplug Charger"
	  icon="󰂅"

    if [ ! -f $crit_file ]; then
      $HOME/.config/eww/bar_vertical/scripts/event_handler crit bat bat on
    fi
  else
	  icon="󰂃"

    if [ -f $crit_file ]; then
      $HOME/.config/eww/bar_vertical/scripts/event_handler crit bat bat off
    fi
  fi
elif [ "$per" -gt "90" ]; then
  if [ $(cat "$bat/status") = Charging ]; then
	  [ ! -f /tmp/eww_states/notify.lock ] && notify-send -t 2000 "Battery Full" "Unplug Charger"
	  icon="󰂋"

    if [ ! -f $crit_file ]; then
      $HOME/.config/eww/bar_vertical/scripts/event_handler crit bat bat on
    fi
  else
	  icon="󰂂"

    if [ -f $crit_file ]; then
      $HOME/.config/eww/bar_vertical/scripts/event_handler crit bat bat off
    fi
  fi
elif [ "$per" -gt "80" ]; then
  if [ $(cat "$bat/status") = Charging ]; then
	  icon="󰂊"
  else
	  icon="󰂁"
  fi
elif [ "$per" -gt "70" ]; then
  if [ $(cat "$bat/status") = Charging ]; then
	  icon="󰢞"
  else
	  icon="󰂀"
  fi
elif [ "$per" -gt "60" ]; then
  if [ $(cat "$bat/status") = Charging ]; then
	  icon="󰂉"
  else
	  icon="󰁿"
  fi
elif [ "$per" -gt "50" ]; then
  if [ $(cat "$bat/status") = Charging ]; then
	  icon="󰢝"
  else
	  icon="󰁾"
  fi
elif [ "$per" -gt "40" ]; then
  if [ $(cat "$bat/status") = Charging ]; then
	  icon="󰂈"
  else
	  icon="󰁽"
  fi
elif [ "$per" -gt "30" ]; then
  if [ $(cat "$bat/status") = Charging ]; then
	  icon="󰂇"
  else
	  icon="󰁼"
  fi
elif [ "$per" -gt "20" ]; then
  if [ $(cat "$bat/status") = Charging ]; then
	  icon="󰂆"
  else
	  icon="󰁻"
  fi
elif [ "$per" -gt "10" ]; then
  if [ $(cat "$bat/status") = Charging ]; then
	  icon="󰢜"

    if [ -f $crit_file ]; then
      $HOME/.config/eww/bar_vertical/scripts/event_handler crit bat bat off
    fi
  else
	  icon="󰁺"
  fi
elif [ "$per" -gt "0" ]; then
  if [ $(cat "$bat/status") = Charging ]; then
	  icon="󰢟"

    if [ -f $crit_file ]; then
      $HOME/.config/eww/bar_vertical/scripts/event_handler crit bat bat off
    fi
  else
	  [ ! -f /tmp/eww_states/notify.lock ] && notify-send -t 2000 -u critical "Battery Low" "Connect Charger"
	  icon="󱃍"

    if [ ! -f $crit_file ]; then
      $HOME/.config/eww/bar_vertical/scripts/event_handler crit bat bat on
    fi
  fi
fi
echo "$icon"
}

percent() {
echo $per
}

mouse() {
  BAT_STATUS=$(dbus-send --print-reply=literal --system --dest=org.bluez /org/bluez/hci0/dev_76_68_56_00_00_9E org.freedesktop.DBus.Properties.Get string:"org.bluez.Battery1" string:"Percentage" 2> /dev/null | awk '{print $3}')

  if [ "$?" == 0 ]; then
   notify-send "${BAT_STATUS}%"
  else
    notify-send "-"
  fi
}

remaining() {
  notify-send $(acpi | awk '{print $5}')
}

toggle_notify_lock() {
  if [ -f /tmp/eww_states/notify.lock ]; then
    rm /tmp/eww_states/notify.lock
  else
    touch /tmp/eww_states/notify.lock
  fi
}

[ "$1" = "icon" ] && icon && exit
[ "$1" = "percent" ] && percent && exit
[ "$1" = "mouse" ] && mouse && exit
[ "$1" = "remaining" ] && remaining && exit
[ "$1" = "toggle_notify_lock" ] && toggle_notify_lock && exit
exit
