#!/bin/bash

hidden=/tmp/syshide.lock

case "$1" in
    -t | --toggle)
        tray_toggle() {
            if [[ $(pidof stalonetray) ]]; then
                if [[ ! -e $hidden ]]; then
                    xdo hide -N stalonetray
                    touch "$hidden"
                else
                    xdo show -N stalonetray
                    xdo raise -N stalonetray
                    rm "$hidden"
                fi
            else
                stalonetray --config $HOME/.config/stalonetrayrc &
            fi
        }
        tray_toggle
        ;;
    -c|--check)
        tray_state(){
            if [[ -e $hidden ]]; then
                echo ""
            else
                echo ""
            fi
        }
        tray_state
        ;;
esac
