#!/bin/bash

# For debugging
# set -x

VIM="nvim"

if [[ "${1}" == "" ]]; then
  start_state='start:reload:echo ""'
else
  start_state="start:reload:rg --column --color=always --smart-case '${1}'"
fi

results=($(
  fzf -m --disabled --ansi \
    --query "${1}" \
    --delimiter ':' \
    --bind "$start_state" \
    --bind 'change:reload:[[ {q} == "" ]] || rg --column --color=always --smart-case {q} || true' \
    --bind "E:execute:${VIM} {1} +{2}" \
    --preview '[[ {1} == ""  ]] || bat --style=numbers --color=always --highlight-line {2} {1}' \
    --preview-window '+{2}-5,<80(up)' | awk -F: '{print $1":"$2}'
))

vim_command="${VIM}"

for ((i=0;i<${#results[@]};i++)); do
  filepath=$(echo "${results[${i}]}" | awk -F: '{print $1}')
  fileline=$(echo "${results[${i}]}" | awk -F: '{print $2}')

  if [[ "${filepath}" == "" ]]; then
    break
  fi

  next_file_arg="+\"e +${fileline} ${filepath}\""
  vim_command="${vim_command} ${next_file_arg}"
done

if [[ "${vim_command}" != "${VIM}" ]]; then
  vim_command="${vim_command} +\"bnext\""
  eval "${vim_command}"
fi

