#!/usr/bin/env bash

direction="$1"
sense="$2"
# countersense is a real word, right?
if [ "$sense" = "+" ]; then
	countersense="-"
else
	countersense="+"
fi

if [ "$direction" = "x" ]; then
	bspc node --resize "right" "${sense}20" "0" ||
	bspc node --resize "left" "${countersense}20" "0"
else
	bspc node --resize "bottom" "0" "${sense}20" ||
	bspc node --resize "top" "0" "${countersense}20"
fi

